[package]
name = "solarsoft_gpu"
version = "0.2.0"
edition = "2021"

[dependencies]
wgpu = "22.0"
winit = "0.30"
pollster = "0.3"
glam = "0.27"
bytemuck = { version = "1.14", features = ["derive"] }
rand = "0.8"
tobj = { version = "4.0", features = ["async"] }
